export const IMAGES = {
	bg: require("./bg.jpg"),
	w1: require("./w1.jpg"),
	w2: require("./w2.jpg"),
	w3: require("./w3.jpg"),
	w4: require("./w4.jpg"),
	w5: require("./w5.jpg"),
	w6: require("./w6.jpg"),
	a1: require("./a1.png"),
	a2: require("./a2.png"),
	a3: require("./a3.png"),
	a4: require("./a4.png"),
	a5: require("./a5.png"),
	a6: require("./a6.png"),
	a7: require("./a7.png"),
	a8: require("./a8.png"),
	a9: require("./a9.png"),
	c1: require("./c1.png"),
	c2: require("./c2.png"),
	c3: require("./c3.png"),
	c4: require("./c4.png"),
	c5: require("./c5.png"),
	c6: require("./c6.png"),
	c7: require("./c7.png"),
	c8: require("./c8.png"),
	dice: require("./dice.png"),
	lock: require("./lock.png")
};

export type ImageKeys = keyof typeof IMAGES;
