export const FONTS = {
	JostBlack: "Jost-Black",
	JostBlackItalic: "Jost-BlackItalic",
	JostBold: "Jost-Bold",
	JostBoldItalic: "Jost-BoldItalic",
	JostExtraBold: "Jost-ExtraBold",
	JostExtraBoldItalic: "Jost-ExtraBoldItalic",
	JostExtraLight: "Jost-ExtraLight",
	JostExtraLightItalic: "Jost-ExtraLightItalic",
	JostItalic: "Jost-Italic",
	JostLight: "Jost-Light",
	JostLightItalic: "Jost-LightItalic",
	JostMedium: "Jost-Medium",
	JostMediumItalic: "Jost-MediumItalic",
	JostRegular: "Jost-Regular",
	JostSemiBold: "Jost-SemiBold",
	JostSemiBoldItalic: "Jost-SemiBoldItalic",
	JostThin: "Jost-Thin",
	JostThinItalic: "Jost-ThinItalic"
};
