# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'SweetIdeas' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
		# Disable code signing for Pods targets (in CI with manual signing)
		installer.pods_project.targets.each do |t|
			t.build_configurations.each do |bc|
				bc.build_settings['CODE_SIGNING_ALLOWED']  = 'NO'
				bc.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
				bc.build_settings['CODE_SIGN_IDENTITY'] = ''
				bc.build_settings.delete('PROVISIONING_PROFILE_SPECIFIER')
				bc.build_settings.delete('PROVISIONING_PROFILE')
				bc.build_settings.delete('DEVELOPMENT_TEAM')
			end
		end
  end
end
